blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Website
    url: https://blockscape.network
    about: Visit our website for more information
  - name: ğŸ—£ï¸ Discord
    url: https://discord.gg/F7MsbeaHtb
    about: Engage with the Blockscape community